[package]
name = "zkp"
version = "0.1.0"
edition = "2021"

[dependencies]
finite_math = { path = "finite_math" }
rand = "0.9.2"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
