[package]
name = "start_groth16"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-groth16 = "0.5.0"
ark-poly = "0.5.0"
ark-r1cs-std = "0.5.0"
ark-relations = "0.5.1"
ark-snark = "0.5.0"
ark-std = "0.5.0"
groth16 = "0.1.0"
rand = "0.8"
