[package]
name = "ec_math"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = "0.5.0"
ark-ff = "0.5.0"
ark-ec = "0.5.0"
ark-bls12-381 = "0.5.0"
ark-poly = "0.5.0"      # for polynomial commitments
rand = "0.9.2"
rand_chacha = "0.9.0"
