[package]
name = "zkp_with_penderson"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
bls12_381 = "0.8.0"
group = "0.13.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
sha2 = "0.10.9"
